name: "CI"

on:
  push:
  pull_request:

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Format check
        run: nix fmt -- --ci

      - name: Build project
        run: nix build

      - name: Run tests
        run: nix develop --command cargo test --verbose

